document.getElementById('year').textContent = new Date().getFullYear();

// ── Renderers ─────────────────────────────────────────────────────────────────

function renderPhotoGrid(items, containerId, icon, emptyText) {
    const el = document.getElementById(containerId);
    if (!items.length) {
        el.innerHTML = `<div class="life-empty"><i class="fa-solid ${icon}"></i><span>${emptyText}</span></div>`;
        return;
    }
    el.innerHTML = `<div class="neu-photo-grid">${items.map(p => `
        <div class="neu-photo-card">
            <div class="neu-photo-inner">
                <img src="${p.src}" alt="${p.caption || ''}" loading="lazy">
            </div>
            ${p.caption ? `<p class="neu-photo-caption">${p.caption}</p>` : ''}
        </div>`).join('')}</div>`;
}

// Photos load automatically from photos-manifest.json (generated by generate-photos.js)
fetch('photos-manifest.json')
    .then(r => r.json())
    .then(photos => renderPhotoGrid(photos, 'photos-grid', 'fa-camera', 'Add photos to capture_photos/ and push to GitHub'))
    .catch(() => renderPhotoGrid([], 'photos-grid', 'fa-camera', 'Add photos to capture_photos/ and push to GitHub'));

