document.getElementById('year').textContent = new Date().getFullYear();

// ── Drawing & Illustration ────────────────────────────────────────────────────
// Add entries: { src: 'path/to/file.jpg', caption: 'Title or description' }
const drawings = [

];

// ── Renderers ─────────────────────────────────────────────────────────────────

function renderPhotoGrid(items, containerId, icon, emptyText) {
    const el = document.getElementById(containerId);
    if (!items.length) {
        el.innerHTML = `<div class="life-empty"><i class="fa-solid ${icon}"></i><span>${emptyText}</span></div>`;
        return;
    }
    el.innerHTML = `<div class="photo-grid">${items.map(p => `
        <div class="photo-card">
            <img src="${p.src}" alt="${p.caption || ''}" loading="lazy">
            ${p.caption ? `<div class="photo-caption">${p.caption}</div>` : ''}
        </div>`).join('')}</div>`;
}

// Photos load automatically from photos-manifest.json (generated by generate-photos.js)
fetch('photos-manifest.json')
    .then(r => r.json())
    .then(photos => renderPhotoGrid(photos, 'photos-grid', 'fa-camera', 'Add photos to capture_photos/ and push to GitHub'))
    .catch(() => renderPhotoGrid([], 'photos-grid', 'fa-camera', 'Add photos to capture_photos/ and push to GitHub'));

renderPhotoGrid(drawings, 'drawings-grid', 'fa-pen-nib', 'Add drawings to the <code>drawings</code> array in life.js');
